DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS secretcodes;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
      id SERIAL PRIMARY KEY,
      first VARCHAR(255) NOT NULL,
      last VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL,
      image VARCHAR ,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );

CREATE TABLE secretcodes(
      id SERIAL PRIMARY KEY,
      email TEXT NOT NULL,
      code VARCHAR(255) NOT NULL ,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );


CREATE TABLE messages(
id SERIAL PRIMARY KEY,
sender_id INT REFERENCES users(id) NOT NULL,
message VARCHAR NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

